import type { Listing } from './types';

// Demo stock shown before the Supabase backend is connected, so the shop looks
// alive from the very first deploy. Once real listings exist they take over.
// Photos are free-to-use Unsplash images.
const img = (id: string) =>
  `https://images.unsplash.com/${id}?auto=format&fit=crop&w=900&q=80`;

export const SAMPLE_LISTINGS: Listing[] = [
  {
    id: 'sample-1',
    title: 'Vintage 90s Levi’s Denim Jacket',
    description:
      'Gorgeous true-vintage Levi’s trucker jacket. Perfectly broken-in denim with that soft, lived-in feel. No rips or marks — just lovely honest wear. A proper wardrobe staple that goes with everything.',
    price: 42,
    original_price: 68,
    currency: 'GBP',
    category: 'womenswear',
    size: 'M',
    brand: 'Levi’s',
    color: 'Blue',
    condition: 'Excellent',
    status: 'active',
    images: [img('photo-1516762689617-e1cffcef479d'), img('photo-1544022613-e87ca75a784a')],
    created_at: new Date(Date.now() - 1000 * 60 * 60 * 3).toISOString(),
  },
  {
    id: 'sample-2',
    title: 'Floral Tea Dress — Summer Ready',
    description:
      'The prettiest ditsy floral tea dress. Flattering wrap waist and a twirl-worthy skirt. Worn once to a garden party, freshly laundered and ready for its next adventure.',
    price: 24,
    original_price: null,
    currency: 'GBP',
    category: 'womenswear',
    size: 'S',
    brand: 'Zara',
    color: 'Pink',
    condition: 'New without tags',
    status: 'active',
    images: [img('photo-1595777457583-95e059d581b8'), img('photo-1572804013309-59a88b7e92f1')],
    created_at: new Date(Date.now() - 1000 * 60 * 60 * 20).toISOString(),
  },
  {
    id: 'sample-3',
    title: 'Chunky Cream Knit Jumper',
    description:
      'Snuggly oversized cable knit in a soft cream. Cosy without being bulky. Absolutely no bobbling. Perfect with jeans and boots for those crisp autumn days.',
    price: 18,
    original_price: 30,
    currency: 'GBP',
    category: 'womenswear',
    size: 'L',
    brand: 'H&M',
    color: 'Cream',
    condition: 'Good',
    status: 'active',
    images: [img('photo-1576871337622-98d48d1cf531'), img('photo-1434389677669-e08b4cac3105')],
    created_at: new Date(Date.now() - 1000 * 60 * 60 * 26).toISOString(),
  },
  {
    id: 'sample-4',
    title: 'Classic Leather Crossbody Bag',
    description:
      'Timeless tan leather crossbody with gold hardware. Roomy enough for all your essentials. A tiny bit of patina that only adds to the charm. Adjustable strap.',
    price: 35,
    original_price: null,
    currency: 'GBP',
    category: 'bags',
    size: null,
    brand: 'Fossil',
    color: 'Tan',
    condition: 'Excellent',
    status: 'active',
    images: [img('photo-1584917865442-de89df76afd3'), img('photo-1548036328-c9fa89d128fa')],
    created_at: new Date(Date.now() - 1000 * 60 * 60 * 40).toISOString(),
  },
  {
    id: 'sample-5',
    title: 'White Leather Trainers',
    description:
      'Fresh white trainers, cleaned and ready to go. Minimal wear on the soles. Comfy everyday sneaker that pairs with literally anything.',
    price: 28,
    original_price: 45,
    currency: 'GBP',
    category: 'shoes',
    size: 'UK 6',
    brand: 'Nike',
    color: 'White',
    condition: 'Good',
    status: 'active',
    images: [img('photo-1595950653106-6c9ebd614d3a'), img('photo-1600185365483-26d7a4cc7519')],
    created_at: new Date(Date.now() - 1000 * 60 * 60 * 52).toISOString(),
  },
  {
    id: 'sample-6',
    title: 'Silk Scarf — Blush Pink',
    description:
      'Luxurious blush silk scarf with a delicate print. Wear it in your hair, on your bag, or around your neck. Adds instant polish to any outfit.',
    price: 12,
    original_price: null,
    currency: 'GBP',
    category: 'accessories',
    size: null,
    brand: null,
    color: 'Pink',
    condition: 'New with tags',
    status: 'active',
    images: [img('photo-1601924994987-69e26d50dc26'), img('photo-1606760227091-3dd870d97f1d')],
    created_at: new Date(Date.now() - 1000 * 60 * 60 * 60).toISOString(),
  },
  {
    id: 'sample-7',
    title: 'Gold Hoop Earrings',
    description:
      'Everyday gold-tone hoops with a lovely weight to them. Hypoallergenic posts. The kind of earrings you put on and never take off.',
    price: 9,
    original_price: 15,
    currency: 'GBP',
    category: 'jewellery',
    size: null,
    brand: null,
    color: 'Gold',
    condition: 'New with tags',
    status: 'active',
    images: [img('photo-1635767798638-3e25273a8236'), img('photo-1611591437281-460bfbe1220a')],
    created_at: new Date(Date.now() - 1000 * 60 * 60 * 72).toISOString(),
  },
  {
    id: 'sample-8',
    title: 'Kids’ Rainbow Raincoat (Age 4-5)',
    description:
      'Adorable and practical rainbow raincoat. Fully waterproof with a cosy hood. Only outgrown, barely worn. Will brighten up any rainy school run.',
    price: 11,
    original_price: null,
    currency: 'GBP',
    category: 'kids',
    size: '4-5y',
    brand: 'Next',
    color: 'Multi',
    condition: 'Excellent',
    status: 'active',
    images: [img('photo-1503919545889-aef636e10ad4'), img('photo-1522771930-78848d9293e8')],
    created_at: new Date(Date.now() - 1000 * 60 * 60 * 90).toISOString(),
  },
  {
    id: 'sample-9',
    title: 'Tailored Wool Blazer',
    description:
      'Sharp navy wool-blend blazer. Beautifully structured shoulders and a nipped-in waist. Dress it up for work or throw over a tee. Dry-cleaned and immaculate.',
    price: 32,
    original_price: 55,
    currency: 'GBP',
    category: 'womenswear',
    size: 'M',
    brand: 'Mango',
    color: 'Navy',
    condition: 'Excellent',
    status: 'reserved',
    images: [img('photo-1591047139829-d91aecb6caea'), img('photo-1507680434567-5739c80be1ac')],
    created_at: new Date(Date.now() - 1000 * 60 * 60 * 120).toISOString(),
  },
  {
    id: 'sample-10',
    title: 'Men’s Checked Flannel Shirt',
    description:
      'Soft brushed-cotton flannel in a classic red check. Super warm and endlessly versatile. Great condition, no missing buttons.',
    price: 15,
    original_price: null,
    currency: 'GBP',
    category: 'menswear',
    size: 'L',
    brand: 'Uniqlo',
    color: 'Red',
    condition: 'Good',
    status: 'active',
    images: [img('photo-1602810318383-e386cc2a3ccf'), img('photo-1589310243389-96a5483213a8')],
    created_at: new Date(Date.now() - 1000 * 60 * 60 * 140).toISOString(),
  },
  {
    id: 'sample-11',
    title: 'Ceramic Vase — Handmade',
    description:
      'A one-of-a-kind handmade ceramic vase in soft neutral tones. Perfect for dried stems or fresh blooms. A little characterful wobble that shows it’s the real deal.',
    price: 22,
    original_price: null,
    currency: 'GBP',
    category: 'home',
    size: null,
    brand: null,
    color: 'Beige',
    condition: 'Excellent',
    status: 'active',
    images: [img('photo-1578500494198-246f612d3b3d'), img('photo-1493106641515-6b5631de4bb9')],
    created_at: new Date(Date.now() - 1000 * 60 * 60 * 160).toISOString(),
  },
  {
    id: 'sample-12',
    title: 'Quilted Puffer Gilet',
    description:
      'Lightweight quilted gilet in a gorgeous dusky pink. Adds a layer of warmth without the bulk. Zips up smooth, no snags. A cosy autumn favourite.',
    price: 20,
    original_price: 34,
    currency: 'GBP',
    category: 'womenswear',
    size: 'S',
    brand: 'New Look',
    color: 'Pink',
    condition: 'Excellent',
    status: 'sold',
    images: [img('photo-1548624313-0396c75f8f1d'), img('photo-1434389677669-e08b4cac3105')],
    created_at: new Date(Date.now() - 1000 * 60 * 60 * 200).toISOString(),
  },
];
